apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep-two
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "1000000"
    volumeMounts:
    - name: nfs-blob-two
      mountPath: "/mnt"
  volumes:
  - name: nfs-blob-two
    persistentVolumeClaim:
      claimName: nfs-blob-two-pvc